/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Employees */
        get: operations["list_employees_api_v1_employees_get"];
        put?: never;
        /** Create Employee */
        post: operations["create_employee_api_v1_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee */
        get: operations["get_employee_api_v1_employees__employee_id__get"];
        put?: never;
        post?: never;
        /** Delete Employee */
        delete: operations["delete_employee_api_v1_employees__employee_id__delete"];
        options?: never;
        head?: never;
        /** Update Employee */
        patch: operations["update_employee_api_v1_employees__employee_id__patch"];
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Employee */
        post: operations["restore_employee_api_v1_employees__employee_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/deletion-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deletion Preview */
        get: operations["deletion_preview_api_v1_employees__employee_id__deletion_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/manager": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reassign Manager */
        put: operations["reassign_manager_api_v1_employees__employee_id__manager_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/subtree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subtree */
        get: operations["get_subtree_api_v1_employees__employee_id__subtree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/reporting-line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reporting Line */
        get: operations["get_reporting_line_api_v1_employees__employee_id__reporting_line_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee Audit */
        get: operations["get_employee_audit_api_v1_employees__employee_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditLogPage */
        AuditLogPage: {
            /** Items */
            items: components["schemas"]["AuditLogRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** AuditLogRead */
        AuditLogRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /** Action */
            action: string;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** EmployeeCreate */
        EmployeeCreate: {
            /** Employee Number */
            employee_number: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Position */
            position: string;
            /** Salary */
            salary: number | string;
            /**
             * Currency
             * @default ZAR
             */
            currency: string;
            /** Manager Id */
            manager_id?: string | null;
            /** Avatar Override Url */
            avatar_override_url?: string | null;
        };
        /** EmployeeHierarchyNode */
        EmployeeHierarchyNode: {
            /** Employee */
            employee: components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"];
            /** Depth */
            depth: number;
        };
        /**
         * EmployeeListItemRead
         * @description `EmployeeRead` plus fields only the list endpoint bothers to compute
         *     (§list query in the repository) — a manager's display name in place of
         *     a bare id, and the row's own direct-report count.
         */
        EmployeeListItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Employee Number */
            employee_number: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Position */
            position: string;
            /** Currency */
            currency: string;
            /** Manager Id */
            manager_id: string | null;
            /** Avatar Override Url */
            avatar_override_url: string | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Salary */
            salary: string;
            /** Manager Name */
            manager_name: string | null;
            /** Direct Report Count */
            direct_report_count: number;
        };
        /** EmployeeListItemReadRestricted */
        EmployeeListItemReadRestricted: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Employee Number */
            employee_number: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Position */
            position: string;
            /** Currency */
            currency: string;
            /** Manager Id */
            manager_id: string | null;
            /** Avatar Override Url */
            avatar_override_url: string | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Manager Name */
            manager_name: string | null;
            /** Direct Report Count */
            direct_report_count: number;
        };
        /** EmployeePage */
        EmployeePage: {
            /** Items */
            items: (components["schemas"]["EmployeeListItemRead"] | components["schemas"]["EmployeeListItemReadRestricted"])[];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * EmployeeRead
         * @description Full representation — `hr_admin` only (§9.3).
         */
        EmployeeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Employee Number */
            employee_number: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Position */
            position: string;
            /** Currency */
            currency: string;
            /** Manager Id */
            manager_id: string | null;
            /** Avatar Override Url */
            avatar_override_url: string | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Salary */
            salary: string;
        };
        /**
         * EmployeeReadRestricted
         * @description `viewer` representation. `salary` is not a field here at all, so
         *     it is absent from the serialised payload — never null, never masked.
         */
        EmployeeReadRestricted: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Employee Number */
            employee_number: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Position */
            position: string;
            /** Currency */
            currency: string;
            /** Manager Id */
            manager_id: string | null;
            /** Avatar Override Url */
            avatar_override_url: string | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
        };
        /**
         * EmployeeUpdate
         * @description Partial update — every field optional. `manager_id` deliberately
         *     absent: reassignment is `PUT /employees/{id}/manager` (§6.1), not a
         *     general PATCH field, because it carries its own invariant.
         */
        EmployeeUpdate: {
            /** Employee Number */
            employee_number?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Email */
            email?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Position */
            position?: string | null;
            /** Salary */
            salary?: number | string | null;
            /** Currency */
            currency?: string | null;
            /** Avatar Override Url */
            avatar_override_url?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ManagerReassignRequest */
        ManagerReassignRequest: {
            /** Manager Id */
            manager_id: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_employees_api_v1_employees_get: {
        parameters: {
            query?: {
                /** @description Fuzzy match on first + last name */
                q?: string | null;
                position?: string | null;
                manager_id?: string | null;
                min_salary?: number | string | null;
                max_salary?: number | string | null;
                min_birth_date?: string | null;
                max_birth_date?: string | null;
                /** @description One of: birth_date, created_at, email, employee_number, first_name, last_name, position, salary, updated_at */
                sort?: string;
                order?: "asc" | "desc";
                /** @description 1-indexed page number */
                page?: number;
                page_size?: number;
            };
            header: {
                /** @description Temporary stand-in for a JWT subject (§9.1 not yet built): the id of an existing app_user row to act as. */
                "X-Actor-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_employee_api_v1_employees_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Temporary stand-in for a JWT subject (§9.1 not yet built): the id of an existing app_user row to act as. */
                "X-Actor-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee_api_v1_employees__employee_id__get: {
        parameters: {
            query?: never;
            header: {
                /** @description Temporary stand-in for a JWT subject (§9.1 not yet built): the id of an existing app_user row to act as. */
                "X-Actor-Id": string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_employee_api_v1_employees__employee_id__delete: {
        parameters: {
            query?: {
                policy?: "reparent" | "promote_to_root" | "cascade";
            };
            header: {
                /** @description Temporary stand-in for a JWT subject (§9.1 not yet built): the id of an existing app_user row to act as. */
                "X-Actor-Id": string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_employee_api_v1_employees__employee_id__patch: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
                /** @description Temporary stand-in for a JWT subject (§9.1 not yet built): the id of an existing app_user row to act as. */
                "X-Actor-Id": string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_employee_api_v1_employees__employee_id__restore_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Temporary stand-in for a JWT subject (§9.1 not yet built): the id of an existing app_user row to act as. */
                "X-Actor-Id": string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletion_preview_api_v1_employees__employee_id__deletion_preview_get: {
        parameters: {
            query?: {
                policy?: "reparent" | "promote_to_root" | "cascade";
            };
            header: {
                /** @description Temporary stand-in for a JWT subject (§9.1 not yet built): the id of an existing app_user row to act as. */
                "X-Actor-Id": string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reassign_manager_api_v1_employees__employee_id__manager_put: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
                /** @description Temporary stand-in for a JWT subject (§9.1 not yet built): the id of an existing app_user row to act as. */
                "X-Actor-Id": string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManagerReassignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subtree_api_v1_employees__employee_id__subtree_get: {
        parameters: {
            query?: {
                depth?: number | null;
            };
            header: {
                /** @description Temporary stand-in for a JWT subject (§9.1 not yet built): the id of an existing app_user row to act as. */
                "X-Actor-Id": string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeHierarchyNode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reporting_line_api_v1_employees__employee_id__reporting_line_get: {
        parameters: {
            query?: never;
            header: {
                /** @description Temporary stand-in for a JWT subject (§9.1 not yet built): the id of an existing app_user row to act as. */
                "X-Actor-Id": string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeHierarchyNode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee_audit_api_v1_employees__employee_id__audit_get: {
        parameters: {
            query?: {
                /** @description 1-indexed page number */
                page?: number;
                page_size?: number;
            };
            header: {
                /** @description Temporary stand-in for a JWT subject (§9.1 not yet built): the id of an existing app_user row to act as. */
                "X-Actor-Id": string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
