/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Employees */
        get: operations["list_employees_api_v1_employees_get"];
        put?: never;
        /** Create Employee */
        post: operations["create_employee_api_v1_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions */
        get: operations["list_positions_api_v1_employees_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee */
        get: operations["get_employee_api_v1_employees__employee_id__get"];
        put?: never;
        post?: never;
        /** Delete Employee */
        delete: operations["delete_employee_api_v1_employees__employee_id__delete"];
        options?: never;
        head?: never;
        /** Update Employee */
        patch: operations["update_employee_api_v1_employees__employee_id__patch"];
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload Employee Avatar */
        put: operations["upload_employee_avatar_api_v1_employees__employee_id__avatar_put"];
        post?: never;
        /** Remove Employee Avatar */
        delete: operations["remove_employee_avatar_api_v1_employees__employee_id__avatar_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Employee */
        post: operations["restore_employee_api_v1_employees__employee_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/deletion-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deletion Preview */
        get: operations["deletion_preview_api_v1_employees__employee_id__deletion_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/manager": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reassign Manager */
        put: operations["reassign_manager_api_v1_employees__employee_id__manager_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/subtree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subtree */
        get: operations["get_subtree_api_v1_employees__employee_id__subtree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/reporting-line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reporting Line */
        get: operations["get_reporting_line_api_v1_employees__employee_id__reporting_line_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee Audit */
        get: operations["get_employee_audit_api_v1_employees__employee_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hierarchy/roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roots */
        get: operations["get_roots_api_v1_hierarchy_roots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Employees */
        post: operations["import_employees_api_v1_imports_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/employees.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Employees Csv */
        get: operations["export_employees_csv_api_v1_exports_employees_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/org-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Org Summary */
        get: operations["get_org_summary_api_v1_analytics_org_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/branch/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Branch Summary */
        get: operations["get_branch_summary_api_v1_analytics_branch__employee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Log */
        get: operations["list_audit_log_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload Profile Avatar */
        put: operations["upload_profile_avatar_api_v1_profile_avatar_put"];
        post?: never;
        /** Remove Profile Avatar */
        delete: operations["remove_profile_avatar_api_v1_profile_avatar_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/avatars/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Avatar */
        get: operations["get_avatar_api_v1_avatars__image_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnomaliesRead */
        AnomaliesRead: {
            /** Wide Spans */
            wide_spans: components["schemas"]["WideSpanAnomalyRead"][];
            /** Single Report Managers */
            single_report_managers: components["schemas"]["SingleReportAnomalyRead"][];
            /** Deep Chains */
            deep_chains: components["schemas"]["DeepChainAnomalyRead"][];
            /** Unreachable */
            unreachable: components["schemas"]["UnreachableAnomalyRead"][];
        };
        /** AuditLogPage */
        AuditLogPage: {
            /** Items */
            items: components["schemas"]["AuditLogRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** AuditLogRead */
        AuditLogRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /** Actor Email */
            actor_email: string;
            /** Action */
            action: string;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Salary Changed */
            salary_changed: boolean;
            /** Manager Before Name */
            manager_before_name?: string | null;
            /** Manager After Name */
            manager_after_name?: string | null;
        };
        /** Body_import_employees_api_v1_imports_employees_post */
        Body_import_employees_api_v1_imports_employees_post: {
            /** File */
            file: string;
        };
        /** Body_upload_employee_avatar_api_v1_employees__employee_id__avatar_put */
        Body_upload_employee_avatar_api_v1_employees__employee_id__avatar_put: {
            /** File */
            file: string;
        };
        /** Body_upload_profile_avatar_api_v1_profile_avatar_put */
        Body_upload_profile_avatar_api_v1_profile_avatar_put: {
            /** File */
            file: string;
        };
        /** BranchEmployeeRead */
        BranchEmployeeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: string;
        };
        /** BranchSummaryRead */
        BranchSummaryRead: {
            employee: components["schemas"]["BranchEmployeeRead"];
            /** Headcount */
            headcount: number;
            /** Direct Reports */
            direct_reports: number;
            /** Depth Below */
            depth_below: number;
            /** Average Span Of Control */
            average_span_of_control: number;
            cost: components["schemas"]["CostSummaryRead"];
        };
        /** BranchSummaryReadRestricted */
        BranchSummaryReadRestricted: {
            employee: components["schemas"]["BranchEmployeeRead"];
            /** Headcount */
            headcount: number;
            /** Direct Reports */
            direct_reports: number;
            /** Depth Below */
            depth_below: number;
            /** Average Span Of Control */
            average_span_of_control: number;
        };
        /** CostSummaryRead */
        CostSummaryRead: {
            /** Total Annual */
            total_annual: string;
            /** Average */
            average: string;
            /** Median */
            median: string;
            /**
             * Currency
             * @default ZAR
             */
            currency: string;
        };
        /** DeepChainAnomalyRead */
        DeepChainAnomalyRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: string;
            /** Depth */
            depth: number;
        };
        /** DepthCountRead */
        DepthCountRead: {
            /** Depth */
            depth: number;
            /** Count */
            count: number;
        };
        /** EmployeeCreate */
        EmployeeCreate: {
            /** Employee Number */
            employee_number: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Position */
            position: string;
            /** Salary */
            salary: number | string;
            /**
             * Currency
             * @default ZAR
             */
            currency: string;
            /** Manager Id */
            manager_id?: string | null;
            /** Avatar Override Url */
            avatar_override_url?: string | null;
        };
        /** EmployeeHierarchyNode */
        EmployeeHierarchyNode: {
            /** Employee */
            employee: components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"];
            /** Depth */
            depth: number;
        };
        /** EmployeeListItemRead */
        EmployeeListItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Employee Number */
            employee_number: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Position */
            position: string;
            /** Currency */
            currency: string;
            /** Manager Id */
            manager_id: string | null;
            /** Avatar Override Url */
            avatar_override_url: string | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Salary */
            salary: string;
            /** Manager Name */
            manager_name: string | null;
            /** Direct Report Count */
            direct_report_count: number;
            /** Avatar Url */
            readonly avatar_url: string;
        };
        /** EmployeeListItemReadRestricted */
        EmployeeListItemReadRestricted: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Employee Number */
            employee_number: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Position */
            position: string;
            /** Currency */
            currency: string;
            /** Manager Id */
            manager_id: string | null;
            /** Avatar Override Url */
            avatar_override_url: string | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Manager Name */
            manager_name: string | null;
            /** Direct Report Count */
            direct_report_count: number;
            /** Avatar Url */
            readonly avatar_url: string;
        };
        /** EmployeePage */
        EmployeePage: {
            /** Items */
            items: (components["schemas"]["EmployeeListItemRead"] | components["schemas"]["EmployeeListItemReadRestricted"])[];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** EmployeeRead */
        EmployeeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Employee Number */
            employee_number: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Position */
            position: string;
            /** Currency */
            currency: string;
            /** Manager Id */
            manager_id: string | null;
            /** Avatar Override Url */
            avatar_override_url: string | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Salary */
            salary: string;
            /** Avatar Url */
            readonly avatar_url: string;
        };
        /** EmployeeReadRestricted */
        EmployeeReadRestricted: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Employee Number */
            employee_number: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Position */
            position: string;
            /** Currency */
            currency: string;
            /** Manager Id */
            manager_id: string | null;
            /** Avatar Override Url */
            avatar_override_url: string | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Avatar Url */
            readonly avatar_url: string;
        };
        /** EmployeeUpdate */
        EmployeeUpdate: {
            /** Employee Number */
            employee_number?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Email */
            email?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Position */
            position?: string | null;
            /** Salary */
            salary?: number | string | null;
            /** Currency */
            currency?: string | null;
            /** Avatar Override Url */
            avatar_override_url?: string | null;
        };
        /** GlobalAuditLogPage */
        GlobalAuditLogPage: {
            /** Items */
            items: components["schemas"]["GlobalAuditLogRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** GlobalAuditLogRead */
        GlobalAuditLogRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /** Actor Email */
            actor_email: string;
            /** Action */
            action: string;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Salary Changed */
            salary_changed: boolean;
            /** Manager Before Name */
            manager_before_name?: string | null;
            /** Manager After Name */
            manager_after_name?: string | null;
            /** Employee Name */
            employee_name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResult */
        ImportResult: {
            /** Rows */
            rows: components["schemas"]["ImportRowResult"][];
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Blocked */
            blocked: number;
            /** Committed */
            committed: boolean;
        };
        /** ImportRowResult */
        ImportRowResult: {
            /** Row Number */
            row_number: number;
            /** Employee Number */
            employee_number: string | null;
            /** Name */
            name: string | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "will_create" | "will_update" | "blocked";
            /** Reason */
            reason: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ManagerReassignRequest */
        ManagerReassignRequest: {
            /** Manager Id */
            manager_id: string | null;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Avatar Url */
            avatar_url: string;
            /** Can View Salary */
            can_view_salary: boolean;
            /** Can Edit */
            can_edit: boolean;
        };
        /** OrgSummaryRead */
        OrgSummaryRead: {
            /** Headcount */
            headcount: number;
            /** Root Count */
            root_count: number;
            /** Manager Count */
            manager_count: number;
            /** Individual Contributor Count */
            individual_contributor_count: number;
            /** Max Depth */
            max_depth: number;
            /** Average Span Of Control */
            average_span_of_control: number;
            /** Median Span Of Control */
            median_span_of_control: number;
            /** Depth Distribution */
            depth_distribution: components["schemas"]["DepthCountRead"][];
            /** Span Distribution */
            span_distribution: components["schemas"]["SpanCountRead"][];
            anomalies: components["schemas"]["AnomaliesRead"];
            cost: components["schemas"]["CostSummaryRead"];
        };
        /** OrgSummaryReadRestricted */
        OrgSummaryReadRestricted: {
            /** Headcount */
            headcount: number;
            /** Root Count */
            root_count: number;
            /** Manager Count */
            manager_count: number;
            /** Individual Contributor Count */
            individual_contributor_count: number;
            /** Max Depth */
            max_depth: number;
            /** Average Span Of Control */
            average_span_of_control: number;
            /** Median Span Of Control */
            median_span_of_control: number;
            /** Depth Distribution */
            depth_distribution: components["schemas"]["DepthCountRead"][];
            /** Span Distribution */
            span_distribution: components["schemas"]["SpanCountRead"][];
            anomalies: components["schemas"]["AnomaliesRead"];
        };
        /** ProfileEmployee */
        ProfileEmployee: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Position */
            position: string;
            /** Avatar Url */
            avatar_url: string;
            /** Employee Number */
            employee_number: string;
            /** Email */
            email: string;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
            manager: components["schemas"]["ProfilePerson"] | null;
            /** Direct Reports */
            direct_reports: components["schemas"]["ProfilePerson"][];
        };
        /** ProfilePerson */
        ProfilePerson: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Position */
            position: string;
            /** Avatar Url */
            avatar_url: string;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Can View Salary */
            can_view_salary: boolean;
            /** Can Edit */
            can_edit: boolean;
            /** Avatar Url */
            avatar_url: string;
            /** Gravatar Url */
            gravatar_url: string;
            /** Has Uploaded Avatar */
            has_uploaded_avatar: boolean;
            employee: components["schemas"]["ProfileEmployee"] | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** SearchResultRead */
        SearchResultRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Position */
            position: string;
            /** Employee Number */
            employee_number: string;
            /** Avatar Url */
            avatar_url: string;
        };
        /** SingleReportAnomalyRead */
        SingleReportAnomalyRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: string;
            /** Direct Reports */
            direct_reports: number;
        };
        /** SpanCountRead */
        SpanCountRead: {
            /** Direct Reports */
            direct_reports: number;
            /** Manager Count */
            manager_count: number;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UnreachableAnomalyRead */
        UnreachableAnomalyRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WideSpanAnomalyRead */
        WideSpanAnomalyRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: string;
            /** Direct Reports */
            direct_reports: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_employees_api_v1_employees_get: {
        parameters: {
            query?: {
                /** @description Fuzzy match on first + last name */
                q?: string | null;
                position?: string | null;
                manager_id?: string | null;
                min_salary?: number | string | null;
                max_salary?: number | string | null;
                min_birth_date?: string | null;
                max_birth_date?: string | null;
                /** @description List soft-deleted employees instead of active ones */
                deleted?: boolean;
                /** @description One of: birth_date, created_at, email, employee_number, first_name, last_name, position, salary, updated_at */
                sort?: string;
                order?: "asc" | "desc";
                /** @description 1-indexed page number */
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_employee_api_v1_employees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_v1_employees_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_employee_api_v1_employees__employee_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_employee_api_v1_employees__employee_id__delete: {
        parameters: {
            query?: {
                policy?: "reparent" | "promote_to_root" | "cascade";
            };
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_employee_api_v1_employees__employee_id__patch: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_employee_avatar_api_v1_employees__employee_id__avatar_put: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_employee_avatar_api_v1_employees__employee_id__avatar_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_employee_avatar_api_v1_employees__employee_id__avatar_delete: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_employee_api_v1_employees__employee_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletion_preview_api_v1_employees__employee_id__deletion_preview_get: {
        parameters: {
            query?: {
                policy?: "reparent" | "promote_to_root" | "cascade";
            };
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reassign_manager_api_v1_employees__employee_id__manager_put: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManagerReassignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subtree_api_v1_employees__employee_id__subtree_get: {
        parameters: {
            query?: {
                depth?: number | null;
            };
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeHierarchyNode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reporting_line_api_v1_employees__employee_id__reporting_line_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeHierarchyNode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee_audit_api_v1_employees__employee_id__audit_get: {
        parameters: {
            query?: {
                /** @description 1-indexed page number */
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roots_api_v1_hierarchy_roots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["EmployeeRead"] | components["schemas"]["EmployeeReadRestricted"])[];
                };
            };
        };
    };
    import_employees_api_v1_imports_employees_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_employees_api_v1_imports_employees_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_employees_csv_api_v1_exports_employees_csv_get: {
        parameters: {
            query?: {
                /** @description Fuzzy match on first + last name */
                q?: string | null;
                position?: string | null;
                manager_id?: string | null;
                min_salary?: number | string | null;
                max_salary?: number | string | null;
                min_birth_date?: string | null;
                max_birth_date?: string | null;
                /** @description List soft-deleted employees instead of active ones */
                deleted?: boolean;
                /** @description One of: birth_date, created_at, email, employee_number, first_name, last_name, position, salary, updated_at */
                sort?: string;
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_org_summary_api_v1_analytics_org_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSummaryRead"] | components["schemas"]["OrgSummaryReadRestricted"];
                };
            };
        };
    };
    get_branch_summary_api_v1_analytics_branch__employee_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchSummaryRead"] | components["schemas"]["BranchSummaryReadRestricted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_log_api_v1_audit_get: {
        parameters: {
            query?: {
                /** @description 1-indexed page number */
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalAuditLogPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    upload_profile_avatar_api_v1_profile_avatar_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_profile_avatar_api_v1_profile_avatar_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_profile_avatar_api_v1_profile_avatar_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    get_avatar_api_v1_avatars__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
